### ISSUE TITLE
feat: layout

### ISSUE THREAD

**Issue by youdaehoon** [youdaehoon/practice_clone_velog#6]
## 종류  

ISSUE 종류를 선택하세요

- [x] feat

## 내용  

- 내용 명: 내용을 작성해주세요 

##  체크리스트

- [x]  components/Layout
- [x]  pages/main/MainLayout
- [x] pages/detail/DetailLayout

**Comment by hahbr88** [comment]
확인 했고 이슈 닫았습니다
