### ISSUE TITLE
style: common.css 내용 정리

### ISSUE THREAD

**Issue by hahbr88** [youdaehoon/practice_clone_velog#7]
## 종류  

ISSUE 종류를 선택하세요

- [x] style

## 내용  

- 내용 명: 내용을 작성해주세요 

##  체크리스트

- [x]  common.css 파일 내 중복 내용 삭제
- [x]  common.css 에 자주쓰는 스타일 class 로 정리 
- [x]  common.css cursor:pointer추가 classname=pointer

**Comment by hahbr88** [comment]
@youdaehoon 이슈 닫으려고 합니다 확인부탁드립니다.

**Comment by youdaehoon** [comment]
@hahbr88  확인했습니다.

**Comment by youdaehoon** [comment]
@hahbr88  확인했습니다.!
